version: 1
services:
  - type: web
    name: my-service
    env: python
    buildCommand: |
      pip install --upgrade pip==24.2
      pip install -r requirements.txt
    startCommand: gunicorn myapp.wsgi:application
