version: 1
services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: |
      pip install --upgrade pip==24.2
      pip install -r requirements.txt
    startCommand: gunicorn your_app.wsgi:application  # Adjust as needed
