# Generated by Django 4.2.16 on 2024-09-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('tshirt', 'T-Shirt'), ('jeans', 'Jeans'), ('jacket', 'Jacket'), ('sweater', 'Sweater'), ('shoes', 'Shoes')], max_length=50)),
                ('size', models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=20)),
                ('image_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
