# Generated by Django 4.2.16 on 2024-09-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0002_remove_product_size_product_available_sizes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('T-Shirt', 'T-Shirt'), ('Jeans', 'Jeans'), ('Jackets', 'Jackets'), ('Shoes', 'Shoes'), ('Tracksuit', 'Tracksuit')], max_length=50),
        ),
    ]
